### ISSUE TITLE
clarify Socrata APIs referenced in readme and wiki documentation 

### ISSUE THREAD

**Issue by ryan-hall** [allejo/PhpSoda#9]
Write operations to Socrata datasets with the Socrata Open Data API differ from write operations with the more recent [Data Management API](https://socratapublishing.docs.apiary.io/). Specifying which API this library uses helps prevent user confusion. 

Adding something like:

Note: This library supports writing directly to datasets with the Socrata Open Data API. For datasets with one or more data transformations applied to the schema through the Socrata Data Management Experience (the user interface for creating datasets), use the Socrata Data Management API to apply those same transformations to all updates. For more details on when to use SODA vs the Socrata Data Management API, see the [Data Management API documentation](https://socratapublishing.docs.apiary.io)

to the readme and wiki would help clarify expectations when publishing to Socrata.

I'll open a PR with changes.

**Comment by allejo** [comment]
Thanks for the PR!
